
$(info Build is about to start...)


.Target:
ifeq ($(VAR1),)
        $(error "Build is about to start...")
endif

#Since this is first non-dot target, this target will get executed

myTarget:.Target
        @echo "HAIk"

